spring:    
    application:
        name: "generar-ft-de-fs"
    main.allow-bean-definition-overriding: true
        
logging:
    level:
        ROOT: INFO
        com.comerzzia.bricodepot: DEBUG

comerzzia:
    db:
        url: jdbc:mysql://172.16.102.35:33062/czz_bricodepot
        user: czz_bricodepot
        pass: czz_bricodepot
        class: com.mysql.cj.jdbc.Driver
    uid_actividad: "40f314f4-8a6e-4c38-82f6-a95a5c8dd0af"
    csv:
        path: ../correcciones.csv
